### ISSUE TITLE
Add flottbot to awesome-go curation list

### ISSUE THREAD

**Issue by rugwirobaker** [target/flottbot#100]
This is such a great project with some great features that i didn't find elsewhere. The downside is I found it by pure luck. I am suggesting to add it o avelino's [awesome-go](https://github.com/avelino/awesome-go) to make it visible to more people.

**Comment by sjqnn** [comment]
Thanks for the interest in the project! I've looked into that in the past. Unfortunately I don't think the project meets their 'quality standard' quite yet. Snippet from their standard page:
```Tests, where practical. If the library/program is testable, then coverage should be >= 80% for non-data-related packages and >=90% for data related packages. Notice: the tests will be reviewed too. We will check your coverage manually if your package's coverage is just a benchmark results.```
If you find another place to help spread interest let us know!

**Comment by wass3r** [comment]
Related #38

**Comment by wass3r** [comment]
we'll keep this in mind, but given the age of the issue, it might not be soon 🐙
