### ISSUE TITLE
Variable for all remaining args in rule

### ISSUE THREAD

**Issue by johnrengelman** [target/flottbot#107]
The arg matching for a rule only allows for extracting an explicit list of values.
However, some rules might have variable argument lists. For example, `command <command name> <args>`.
It would be helpful, if I could specify a matcher to the remaining arg values:
```
args:
  - cmd
  - cmdArgs+
```
with `cmdArgs` being set to the remaining line after the matches are extracted.
For example, `command nc google.com 443`, would resolve to:
`cmd=nc` and `cmdArgs="google.com 443"`

**Comment by JordanSussman** [comment]
I agree that this type of functionality would be useful. Until someone has the opportunity to implement this, you could potentially use [optional arguments](https://github.com/target/flottbot/pull/86) that is documented [here](https://github.com/target/flottbot-docs/pull/29) until this type of functionality is added. The aforementioned recommendation wouldn't solve all scenarios but could solve common permutations.
