### ISSUE TITLE
Add Telegram support for remote

### ISSUE THREAD

**Issue by mitinarseny** [target/flottbot#109]
It would be nice, if you add support for [Telegram Bot API](http://core.telegram.org/bots/api).

**Comment by wass3r** [comment]
just leaving this here for future reference: https://github.com/go-telegram-bot-api/telegram-bot-api

**Comment by yonnic** [comment]
yes telegram would be a great addon

**Comment by wass3r** [comment]
rudimentary support was added with the above PR - thanks @ormazz . only direct messages work at the moment, however. will keep this open to try and at least add ability to have it respond via channel message as well.

**Comment by huang-jy** [comment]
Even if it doesn't respond via channel message, can it detect messages on channel? e.g. you could have the bot in a channel/group chat and if someone wrote (for example) "!help", the bot would respond directly to the sender rather than in the channel. It would help open up a direct message chat between users and the bot directly.

**Comment by wass3r** [comment]
That's definitely how you can interact right now in Slack and part of the normal feature set. The current, initial Telegram implementation will only allow interaction via direct message with the bot. We will try and get it as close the normal feature set as we can with the Telegram API wrapper. Not sure on timing yet.

**Comment by wass3r** [comment]
https://github.com/target/flottbot/pull/147 should address some or most of the discrepancy with call on the bot from within channels or groups and having the bot respond via DM by using the `direct_message_only` directive in your rule.

**Comment by wass3r** [comment]
i will close this for now. if specific things aren't working or you want to see supported, please open a new issue.
