### ISSUE TITLE
Add an option to disable help message for unknown commands

### ISSUE THREAD

**Issue by renjithpk** [target/flottbot#133]
I have few scenarios where I wanted to silence flottbot for unknown commands

- When I migrate my existing bot to flottbot, I wanted to keep two bot backend and gradually migrate the commands of existing bot to flottbot, but flottbot doesn't have an option to silence unknown command help text.

- I wanted to run flottbot in different cluster, and one of them is primary which acts on all commands, all others will act for few specific commands, but now all bots will respond with help text if there is no matching rule.

**Comment by wass3r** [comment]
closed by #134
