### ISSUE TITLE
Is there  a way work with an arbitrary number of arguments?

### ISSUE THREAD

**Issue by stahnma** [target/flottbot#202]
I'm trying to create a rule with unknown number of arguments (or really, just a long string). 

`aw yiss an unknown number of words can be here`

I want everything after `yiss` and from what I can tell, there isn't a match that is everything that isn't the `respond` pattern. I've been attempting to use sprig template functions to do the replacement, but they seem to be interpreted  as literals (maybe unless it's in the expose_json fields?). 

I tried to use templates in the yaml to do it and that I couldn't make work. I also looked at somehow using optional arguments, but the documentation is sparse and reading the source code it wasn't immediately obvious that could help if I didn't know the number of arguments that would be incoming. 

---

A fix here would be an internally created variable that is like `${_raw_user_input}` but really just `${_raw_arguments}`. I was able to hack that in on my copy, but that doesn't help if it's regex matched vs direct string matched. 

https://github.com/stahnma/flottbot/commit/bafda841a3677d821fe4a9f307b1433533a2a413 (I didn't make a PR because I think discussion is more helpful than just some code right now). 

in core/matcher.go 

`message.Vars["_raw_arguments"] = strings.Replace(message.Input, rule.Respond+" ", "", 1)`

Is there a better way to get the argument values

- without knowing how many there will be
- without having the whole string that includes the matching text?

If not, I can put up a PR for this change and edit docs and such. It's helpful, but not perfect. I think the matching mechanism would be easier to work with if it included regex capture groups, and `hear` rules could have arguments too. (But alas, that's another problem for another day).

**Comment by wass3r** [comment]
I could be misunderstanding, but the closest thing to that is probably what was introduced here: https://github.com/target/flottbot/pull/116

so, if your (partial) rule looked like this:
```yaml
respond: aw

args:
  - first
  - other+
```

assuming the input is: `aw yiss an unknown number of words can be here`

the content would map as follows:
`${first}` = "yiss"
`${other}` = "an unknown number of words can be here"

will that work?

capture groups for regex is definitely something that was/is on the horizon.

i have seen some people implement their own parser script and basically pass `${_raw_user_input}` to an exec action, then you have full control.

but perhaps if the matcher options were more flexible some of those cases could be covered 🤷🏼

**Comment by stahnma** [comment]
That works. (Thanks for waiting on my delayed response).
