### ISSUE TITLE
Discussion: Hear with arguments

### ISSUE THREAD

**Issue by stahnma** [target/flottbot#204]
Is there a reason that `hear` isn't allowed to have arguments? Like is that a design decision or an odd technical limitation? I haven't dug into it too far yet, but thought I'd ask before I started working it up. 

I dislike having to address the bot directly for...many things. I'm pretty used to hubot and it's flexibility so trying to see what I can do to get some of the core functionality to have parity.

**Comment by wass3r** [comment]
this might be addressed with the referenced PR. if not, feel free to reopen. thanks again @justmiles
