### ISSUE TITLE
Remote for Google Chat

### ISSUE THREAD

**Issue by justmiles** [target/flottbot#221]
Relevant docs:
- Google Chat for Developers: [developers.google.com/hangouts/chat](https://developers.google.com/hangouts/chat/)
- Google Chat Code Samples: [github.com/googleworkspace/hangouts-chat-samples](https://github.com/googleworkspace/hangouts-chat-samples)
- Golang Google Chat Package: [pkg.go.dev/google.golang.org/api/chat/v1](https://pkg.go.dev/google.golang.org/api/chat/v1)

**Comment by wass3r** [comment]
added in https://github.com/target/flottbot/pull/223
