### ISSUE TITLE
Fix coveralls to look at all directories 

### ISSUE THREAD

**Issue by JordanSussman** [target/flottbot#34]
Currently https://coveralls.io/github/target/flottbot appears to only be looking at some directories but not all.

**Comment by wass3r** [comment]
I'm not sure what to make of this.. it's definitely including all the files that have tests associated with them (9) and then some random ones (to total 13 files) that are maybe accidentally covered partially by tests? others are completely omitted. maybe it works as intended?

**Comment by JordanSussman** [comment]
I would expect the coveralls tree browser to display our entire fold structure instead of just those with tests. 

For example, https://github.com/target/flottbot/tree/master/remote isn't displayed on the following screenshot.

![screen shot 2018-09-04 at 4 53 50 pm](https://user-images.githubusercontent.com/8935518/45059857-2a232f80-b063-11e8-9cfb-63453480f529.png)

**Comment by wass3r** [comment]
The `coverage.out` file that gets produced matches with what we're seeing at coveralls - probably have to tweak the test command some
