### ISSUE TITLE
Create bot cooldown periods

### ISSUE THREAD

**Issue by JordanSussman** [target/flottbot#35]
Ideally we could implement some sort of cooldown or mute functionality at the bot level. This would be useful for scenarios where you don't want excessive spam.

This functionality could be created at all of the following levels:

- global (entire slack/discord server)
- channel
- user

**Comment by sjqnn** [comment]
Can this just be rolled into #7 ?

**Comment by JordanSussman** [comment]
Yes @sjqnn
