### ISSUE TITLE
New TM looking to help?

### ISSUE THREAD

**Issue by geoff-nixon** [target/flottbot#364]
# Report

## What did you do?
I started working at Target.

## What did you expect to happen?

I expected there would be bugs. And other shitty things.

## What happened instead?

That’s exactly what.

Please complete the following information):

- MyDevice
- MyDay
- ePick
- my own phone

- etc.

## Additional context

Hey kids. Sorry for filing a bug here, but I don’t know where else I should go. I’m a new Target Team Member. In a former life, spent a lot of time coding and fixing other projects’ bugs.

I’d love to be able to contact whoever is in charge of the frigg’n MyDevice in-house  apps (and the public Target app). Like, if there is a way to add me on the internal bug tracker or TestFlight/(full… an Enterprise signed version, like MyTime?).

Or I can fuck off. I file decent bug reports though. And could help identify other inefficiencies. Just thought I’d offer.

**Comment by slushpupie** [comment]
This issue is not adhere to our [code of conduct](https://github.com/target/flottbot/blob/main/.github/CODE_OF_CONDUCT.md).  Closing.
