### ISSUE TITLE
Increase test coverage to >= 80%

### ISSUE THREAD

**Issue by JordanSussman** [target/flottbot#38]
@wass3r brought it down from 72% to 35%. 😉

**Comment by sjqnn** [comment]
looks like this script may help..

https://github.com/gopns/gopns/blob/master/test-coverage.sh

**Comment by sjqnn** [comment]
on second thought this seems cleaner https://github.com/mattn/goveralls/issues/20#issuecomment-72758697

**Comment by wass3r** [comment]
I think we are ok with reporting the coverage accurately now, we just need to write tests to bring the coverage up.

**Comment by wass3r** [comment]
i'm not sure if it makes to keep an issue open for this. closing for now.
