### ISSUE TITLE
Add Mattermost as a remote?

### ISSUE THREAD

**Issue by gfriloux** [target/flottbot#97]
Hello everyone!

I started looking at your bot, and it looks promising to me.
Managing YML files + scripts would make it easier for anyone to contribute to a bot (instead of going through internal bot coding).

Looking at this blog post : https://tech.target.com/chatbot%20framework/2018/10/01/flottbot.html
I see that you consider adding support for mattermost.
This is clearly my case of use.

I have not find any issue for about it, that's why i'm doing it, and i'd like to know if any of you guys have think about a delay for adding it?

**Comment by wass3r** [comment]
Thanks for posting the issue. Good to see interest in that. Yes, we're hoping to add a few networks yet, but would like to complete some refactoring first before doing so.

**Comment by wass3r** [comment]
adding this for future reference: https://github.com/mattermost/mattermost-bot-sample-golang
